#spring:
#  application:
#    name: SpringBootAndDataJpa
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/java16
#    username: postgres
#    password: 1234
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#server:
#  port: 2020